// Not sure yet how to load a script while using atom
s0.initImage("https://upload.wikimedia.org/wikipedia/commons/a/a1/TuringPattern.PNG")
s1.initImage("https://upload.wikimedia.org/wikipedia/commons/2/22/Jelly_Monterey.jpg")
let script = await loadScript("https://cdn.statically.io/gl/metagrowing/extra-shaders-for-hydra/main/lib/all.js")
let dither4 = script.dither4
s2.initImage("https://wiki.xxiivv.com/media/diary/676.jpg")
s3.initImage("https://upload.wikimedia.org/wikipedia/commons/f/ff/ISS-56_International_Space_Station_fly-around_%2805%29.jpg")
src(o2).out()
osc(3, -0.1, () => a.fft[0] * 6)
  .modulateKaleid(
	osc(3, -1), 4
)
  .scale(0.5, 0.5)
  .modulate(noise(5, 0.1))
  .mult(solid(1.7, 1, 1.5))
  .diff(src(s0).modulate(osc(3, 1, 0.7)).kaleid([4, 10, 50].smooth()).dither4())
  .blend(
    src(s1)
    .scrollX(0.1, 0.01)
    .scale([.1, .5, .9].ease("easeInOutCubic").fast(1/16))
    .scrollY(({time}) => Math.sin(time /5))
    .rotate([2, .4, 6].smooth().fast(1/4))
  )
  .diff(o1)
  .add(src(o0).scale([1.1, 0.9]), .1)
  .diff(src(s3).scale([1, 2, 2,], [1, 2, 10]))
  .out(o2)
src(s2)
  .modulate(o0,()=>0.1*Math.sin(time))
  .out(o1)
render()
