s0.initImage("file:///Users/laura/source/github/lauraporta/hydra-p5/images/walk.gif")
src(s0)
  .diff(
    src(s0)
    .rotate(0.2)
  )
  .luma(0.1)
  .modulate(osc(2, 0.01).kaleid(50))
  .modulate(s0)
  .out()
