s0.initVideo("file:///Users/laura/source/github/lauraporta/hydra-p5/images/waves.mp4")
src(s0)
  .scale(1.5, 1, 2)
  .colorama(1, 1, 1)
  .contrast(2)
.out(o0)
src(o0)
  .modulateScale(o1, 0.5)
  .blend(o1, 0.8)
  .out(o1)
shape(4)
  .scale(2.5)
  .mult(o1)
  .out(o2)
render(o2)
